# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-30 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DHT11_readings',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False, unique=True, verbose_name='date and time of reading')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DHT11_sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('about_text', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('sensor_name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('creation_date', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.AddField(
            model_name='dht11_sensor',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensorsHome.Sensor'),
        ),
        migrations.AddField(
            model_name='dht11_readings',
            name='DHT11',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensorsHome.DHT11_sensor'),
        ),
    ]
