# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-31 01:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensorsHome', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dht11_sensor',
            name='sensor',
        ),
        migrations.AddField(
            model_name='sensor',
            name='ip_address',
            field=models.GenericIPAddressField(default='0.1.2.3'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensor_type',
            field=models.CharField(default='sensor', max_length=100),
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensors_text',
            field=models.CharField(default='text', max_length=200),
        ),
        migrations.AlterField(
            model_name='dht11_readings',
            name='DHT11',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensorsHome.Sensor'),
        ),
        migrations.DeleteModel(
            name='DHT11_sensor',
        ),
    ]
