# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-31 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensorsHome', '0003_auto_20170130_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='last_reading',
            field=models.DateTimeField(default='1000-10-10', verbose_name='date and time of latest reading'),
        ),
    ]
