# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-31 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensorsHome', '0004_auto_20170130_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='last_reading',
            field=models.DateTimeField(default='2017-01-31 01:36:51.447617', verbose_name='date and time of latest reading'),
        ),
    ]
