# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-31 02:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sensorsHome', '0005_auto_20170130_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dht11_readings',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 31, 2, 17, 48, 741196, tzinfo=utc), primary_key=True, serialize=False, unique=True, verbose_name='date and time of reading'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='last_reading',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 31, 2, 17, 48, 736350, tzinfo=utc), verbose_name='date and time of latest reading'),
        ),
    ]
