# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-31 02:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sensorsHome', '0006_auto_20170130_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dht11_readings',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, primary_key=True, serialize=False, unique=True, verbose_name='date and time of reading'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='last_reading',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date and time of latest reading'),
        ),
    ]
