# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-31 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensorsHome', '0009_auto_20170130_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dht11_readings',
            name='timestamp',
            field=models.DateTimeField(default='2012-09-04 06:00:00.000000', primary_key=True, serialize=False, unique=True, verbose_name='date and time of reading'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='last_reading',
            field=models.DateTimeField(default='2012-09-04 06:00:00.000000', verbose_name='date and time of latest reading'),
        ),
    ]
