# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-31 02:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sensorsHome', '0011_auto_20170130_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dht11_readings',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='last_reading',
        ),
        migrations.AddField(
            model_name='dht11_readings',
            name='id',
            field=models.AutoField(auto_created=True, default=10, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
