# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-31 03:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sensorsHome', '0013_auto_20170130_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dht11_readings',
            name='timestamp',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='date_created',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
        ),
    ]
