# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-31 03:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sensorsHome', '0014_auto_20170130_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dht11_readings',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, primary_key=True, serialize=False, unique=True, verbose_name='date and time of reading'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date and time created'),
        ),
    ]
