# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-31 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensorsHome', '0015_auto_20170130_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dht11_readings',
            name='humidity',
            field=models.FloatField(default=-1000),
        ),
        migrations.AlterField(
            model_name='dht11_readings',
            name='temperature',
            field=models.FloatField(default=-1000),
        ),
    ]
