# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-31 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensorsHome', '0016_auto_20170130_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date and time created'),
        ),
    ]
