# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-31 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sensorsHome', '0017_auto_20170131_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date and time created'),
        ),
    ]
