# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-05 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensorsHome', '0018_auto_20170131_0708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dht11_readings',
            name='sensor_association',
        ),
        migrations.AlterField(
            model_name='sensor',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date and time created'),
        ),
    ]
