# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-05 04:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensorsHome', '0019_auto_20170204_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='sensors_text',
            new_name='sensor_text',
        ),
    ]
