# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-26 22:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensorsHome', '0021_tsl251_readings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TSl251_readings',
            new_name='TSL2561_readings',
        ),
    ]
