# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=50, unique=True, verbose_name='Title')),
                ('post_text', models.CharField(max_length=5000, verbose_name='Text')),
                ('pub_date', models.DateTimeField(verbose_name='Date Published')),
                ('likes', models.IntegerField(default=0, verbose_name='Likes')),
            ],
        ),
    ]
